var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                                                ",
   "                                             o      o      o       x            ",
   "                                                                                ",
   "                                    o o      x      x      x                    ",
   "                                                               x       x        ",
   "                                   xxxxx                       x!!!!!!!x        ",
   "                           o                                   xxx!!!xxx        ",
   "               o                                                xx!!!xx     xx  ",
   "                            xx           oo           oo        xx!!!xx      x  ",
   "                          xxx                       o    o      xxxvxxx      x  ",
   "                                                                             x  ",
   "                                               #                             x  ",
   "        @                                                       xxx xxx  &   x  ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx      xxxxxx        xxxxxxxx xxxxxxxxxx  ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx      xxxxxx        xxxxxxxx xxxxxxxxxx  ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxx!!!!!!xxxxxx!!!!!!!!xxxxxxxx xxxxxxxxxx  ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxx!!!!!!xxxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxx  ",
   "x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "    % xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                     &          ",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                                                                                ",
   "                                                                                ",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x     x",
   "x                                     x!!x     x",
   "x                                     x!!x     x",
   "x                                     x!!x     x",
   "x                                   # x!!x     x",
   "x @x                                  x!!x     x",
   "xxxxxxxxxxxxxxx    xxxxxxxx  xxxx  xxxxxxx     x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x",
   "x                                              x",
   "x                                 o            x",
   "x                                              x",
   "x              xxxxxxx    xxxx         xxx     x",
   "x             xx     xx       xxx   xxx        x",
   "x            xx       xx        x   x          x",
   "x    @       x         x        x   x          x",
   "x   xxx      x         x        x   x   &      x",
   "x   x x      x         x        x   x  xxx     x",
   "x!!!x x!!!!!!x         x!!!!!!!!x!!!x!!!!!!!!!!x",
   "x!!!x x!!!!!!x         x!!!!!!!!x!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x %                                            x                                  x",
   "xxxxxxxxx      xx      xx     xx               x                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x                                    xx        x                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x                                            xxx                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "x                                              x                                  x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                 x",
   "x                                                                                 x",
   "x                                                                                 x",
   "x                         xx                                                      x",
   "x                                                                                 x",
   "x                                                                                 x",
   "x %   @                                                  #                    &   x",
   "xxxxxxxxxxx   xx   xx   xxxxxx        xxxxxxxxxx         xxxx            xxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                             ",
   "x x xxx x@ x  x   x xxx xx  x",
   "x x x x x  x  x   x  x  x x x",
   "xxx x x x  x  x   x  x  x x x",
   " x  x x x  x  x x x  x  x x x",
   " x  x x x  x  x x x  x  x x x",
   " x  xxx xxxx  xxxxx xxx x  xx",
   "                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
